# Enhanced Multitask ReLA Training Configuration
# For Detection + Segmentation + Pose Estimation on HuMAR Dataset

_BASE_: Base-COCO-InstanceSegmentation.yaml

MODEL:
  META_ARCHITECTURE: "MultitaskGRES"  # Our enhanced multitask model
  
  # Enhanced Detection Head Configuration
  DETECTION_HEAD:
    NAME: "AdvancedDetectionHead"
    HIDDEN_DIM: 256
    NUM_CLASSES: 80  # COCO classes
    NUM_TRANSFORMER_LAYERS: 3
    NUM_ATTENTION_HEADS: 8
    DROPOUT: 0.1
    CONFIDENCE_THRESHOLD: 0.5
    NMS_THRESHOLD: 0.6
    
  # Enhanced Pose Head Configuration  
  POSE_HEAD:
    NAME: "AdvancedPoseHead"
    HIDDEN_DIM: 256
    NUM_KEYPOINTS: 17  # COCO pose keypoints
    NUM_TRANSFORMER_LAYERS: 4
    NUM_ATTENTION_HEADS: 8
    DROPOUT: 0.1
    KEYPOINT_THRESHOLD: 0.3
    POSE_QUALITY_THRESHOLD: 0.5
    
  # Segmentation Head (existing sophisticated architecture)
  SEM_SEG_HEAD:
    NAME: "ReferringHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 80
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
    
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedReferringDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    LANG_ATT_WEIGHT: 0.1
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8

  # Multitask Loss Weights
  MULTITASK:
    DETECTION_LOSS_WEIGHT: 1.0
    SEGMENTATION_LOSS_WEIGHT: 1.0 
    POSE_LOSS_WEIGHT: 1.0
    QUALITY_LOSS_WEIGHT: 0.1
    CONSISTENCY_LOSS_WEIGHT: 0.1

INPUT:
  IMAGE_SIZE: 512  # Increased for better pose estimation
  DATASET_MAPPER_NAME: "multitask_humar"  # Use custom multitask mapper
  # Disable data augmentations
  RANDOM_FLIP: "none"  # Disable random flipping
  MIN_SIZE_TRAIN: (512,)  # Fixed size, no random resizing
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512

DATASETS:
  TRAIN: ("humar_multitask_train",)
  TEST: ("humar_multitask_val",)

SOLVER:
  IMS_PER_BATCH: 8  # Reduced batch size for testB dataset
  BASE_LR: 0.0001   # Slightly higher for multitask learning
  STEPS: (5000, 8000)  # Reduced steps for smaller dataset
  MAX_ITER: 10000   # Much shorter training for testB
  WARMUP_ITERS: 500
  WARMUP_FACTOR: 0.001
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  
  # Enhanced learning schedule for multitask
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POLY_LR_POWER: 0.9
  POLY_LR_CONSTANT_ENDING: 0.0
  
  # Gradient clipping for stability
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False  # Keep all HuMAR samples
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "TrainingSampler"
  
TEST:
  EVAL_PERIOD: 1000  # Evaluate more frequently for shorter training
  
OUTPUT_DIR: "./output/enhanced_multitask_humar"